version: "3.7"

services:
  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data

  app:
    image: demo-ops-app:latest
    depends_on:
      - redis
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

