apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: demo-app:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        resourceRequests:
          cpu: 100m
          memory: 256Mi
        resourceLimits:
          cpu: 200m
          memory: 512Mi
